version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "security-group-fqdn"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4iwr4bd7dybi"
s3_prefix = "security-group-fqdn"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

